### Word Search Efficiency Scratch Work

In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
# reset our data
original_training_data = pd.read_csv('data/train.csv')
original_training_data['email'] = original_training_data['email'].astype('str') 
original_training_data['subject'] = original_training_data['subject'].astype('str') 

In [3]:
def top_counts(data):
    all_words = ' '.join(list(data))
    counts = dict()
    words = all_words.split()
    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1
    counts = pd.Series(list(counts.values()), index=list(counts.keys()))
    counts = counts.sort_values(ascending=False)[:150]
    return set(counts.index)

ham_words_subj = top_counts(original_training_data[original_training_data['spam']==0]['subject'])
spam_words_subj = top_counts(original_training_data[original_training_data['spam']==1]['subject'])
unique_subj = spam_words_subj.symmetric_difference(ham_words_subj)
subj_words = list(unique_subj)

In [4]:
## NEEDS OPTIMIZATION!!! ##
def words_in_texts(words, texts):
    '''
    Args:
        words (list-like): words to find
        texts (Series): strings to search in
    
    Returns:
        NumPy array of 0s and 1s with shape (n, p) where n is the
        number of texts and p is the number of words.
    '''
    indicator_array = np.zeros((len(texts), len(words)))
    for i in range(len(texts)):
        for j in range(len(words)):
            if words[j] in texts[i].split():
                indicator_array[i][j] = 1
    return indicator_array

In [23]:
# make sure to pass in a series

def words_in_texts3(words, texts):
    indicator_array = np.array([pd.Series([1 if word in text else 0 for word in words]) for text in texts])
    return indicator_array

In [16]:
words = ["My", "Name", "Is", "Tyler"]
texts = pd.Series(["Tyler goes to cal", "My dog Is named dexter", "nothing nothing nothing"])
result = words_in_texts3(words, texts)
print(result)

[[0 1 0]
 [0 0 0]
 [0 1 0]
 [1 0 0]]


In [ ]:
# helper function
def create_dict(words):
    d = {}
    for word in words:
        d[word] = 0
    return d

def words_in_texts2(words, texts):
    indicator_array = pd.DataFrame()
    #for i in range(len(texts)):
    for i in range(1):
        words_dict = create_dict(words)
        text = texts[i].split()
        for w in words_dict.keys():
            if w in text:
                words_dict[w] = 1
        indicator_array.insert(i, i, list(words_dict.values()))
    return indicator_array

__The time it takes the below cell to run needs to be minimized:__  
Current time: 23 s  
Viraj time: 51 s

In [22]:
type(original_training_data['subject'][6])

str

In [25]:
%%time
subj_word_df1 = pd.DataFrame(words_in_texts3(subj_words, pd.Series(original_training_data['subject'])), columns=subj_words)
print(subj_word_df1.shape)

(8348, 230)
CPU times: user 2.21 s, sys: 90.8 ms, total: 2.3 s
Wall time: 2.28 s


__Don't run the below cell__

In [17]:
%%time
subj_word_df = pd.DataFrame(words_in_texts(subj_words, original_training_data['subject']), columns=subj_words)
print(subj_word_df.shape)

(8348, 230)
CPU times: user 25.1 s, sys: 303 ms, total: 25.4 s
Wall time: 26.3 s
